package com.utm.rugbyplanner.model;

import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * ChatMessage — MongoDB collection: "chat_messages"
 *
 * UC011: Chat with AI Chatbot
 *
 * Each document stores a single turn of the conversation between
 * a client and the AI chatbot (Ollama llama3.2). Messages are
 * persisted so the chat history can be reloaded when the user
 * revisits the Chatbot view, and so recent turns can be replayed
 * back to the model as conversational context for personalization.
 *
 *   role = "USER"      → message typed by the athlete/trainer
 *   role = "ASSISTANT" → response generated by the chatbot
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "chat_messages")
public class ChatMessage {

    @Id
    private String id;

    @Indexed
    private String userId;   // FK → User._id

    /** "USER" or "ASSISTANT" */
    private String role;

    /** Raw message text */
    private String content;

    @CreatedDate
    private LocalDateTime createdAt;
}
